import type { OpenAPISpec } from "./parseSpec.js";
import { listOperations } from "./parseSpec.js";

export function generateClient(spec: OpenAPISpec, baseUrl = "process.env.API_BASE_URL"): string {
  const ops = listOperations(spec);
  const lines = [
    "// Auto-generated by OpenAPI DevKit (portfolio starter)",
    `export const BASE_URL = ${baseUrl};`,
    "",
  ];

  for (const op of ops) {
    const fnName = op.operationId.replace(/[^a-zA-Z0-9_]/g, "_");
    lines.push(
      `export async function ${fnName}(init?: RequestInit): Promise<Response> {`,
      `  return fetch(\`\${BASE_URL}${op.path}\`, { method: "${op.method}", ...init });`,
      `}`,
      "",
    );
  }

  return lines.join("\n");
}
